# Generated by Django 3.2.9 on 2022-01-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentanswers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswers',
            name='student',
        ),
        migrations.AddField(
            model_name='studentanswers',
            name='studentexam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.studentexam'),
        ),
    ]
