# Generated by Django 4.0.1 on 2022-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_studentanswers_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
