# Generated by Django 4.0.1 on 2022-01-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
