# Generated by Django 4.0.1 on 2022-02-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_exam_subject_alter_studentexam_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='take_again',
            field=models.BooleanField(default=False),
        ),
    ]
