# Generated by Django 4.0.1 on 2022-02-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_studentexam_take_again'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_phone',
            new_name='phone2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='_class',
            field=models.CharField(choices=[('اولي', 'اولي'), ('تانيه علمي', 'تانيه علمي'), ('تانيه ادبي', 'تانيه ادبي'), ('تالته', 'تالته')], max_length=15),
        ),
    ]
