# Generated by Django 4.0.1 on 2022-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_parent_phone_student_phone2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone2',
            new_name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='_class',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('اولي', 'اولي'), ('ثانيه علمي', 'ثانيه علمي'), ('ثانيه ادبي', 'ثانيه ادبي'), ('ثالثه', 'ثالثه')], default='الثالث', max_length=15),
            preserve_default=False,
        ),
    ]
